spring:
   redis: 
      host: 42.192.78.13  #redis.qfjava.cn
      port: 6379 #8400
      password: P@ssword

#  全局关闭hystrix超时：
hystrix:
  command:
    default: 
      execution:
        timeout:
          enabled: false
